name: avalonia-xaml-playground
base: core24
adopt-info: xaml-playground
icon: snap/gui/avalonia-xaml-playground.png
summary: Avalonia XAML and C# playground
description: |
  The Avalonia XAML Playground application allows you to write
  XAML and code-behind pieces of code, with Avalonia controls,
  and seeing the results in real time.

grade: stable
confinement: strict

plugs:
  dotnet-runtime:
    interface: content
    default-provider: dotnet-runtime-80
    content: dotnet-runtime-80
    target: $SNAP/usr/lib

platforms:
  amd64:
      build-on: [amd64]
      build-for: [amd64]
  arm64:
      build-on: [arm64]
      build-for: [arm64]

parts:
  prereqs:
    plugin: nil
    after:
      - xaml-playground
    stage-packages:
      - fontconfig
      - libfontconfig1
      - libice6
      - libicu74
      - libsm6
      - libx11-6

  xaml-playground:
    plugin: dotnet
    source: https://github.com/AvaloniaUI/XamlPlayground
    source-type: git
    build-packages:
      - git
    dotnet-version: "8.0"
    dotnet-configuration: "Release"
    dotnet-project: src/XamlPlayground.NetCore/XamlPlayground.NetCore.csproj
    dotnet-verbosity: "minimal"
    dotnet-properties:
      AvaloniaVersion: 11.2.5
      AvaloniaBehaviorsVersion: 11.2.0.13
      AvaloniaEditVersion: 11.1.0
      OctokitVersion: 14.0.0
      CommunityToolkitMvvmVersion: 8.4.0
    override-build: |
      version=$(git show -s --format=%h)
      craftctl set version="${version}"
      craftctl default
    organize:
      '*': opt/xamlplayground/

  launcher:
    plugin: dump
    source: snap
    organize:
      'launcher.sh' : usr/bin/launcher.sh
    stage:
      - usr/bin/launcher.sh
    override-prime: |
      craftctl default
      chmod a+x usr/bin/launcher.sh

apps:
  avalonia-xaml-playground:
    command: usr/bin/launcher.sh
    desktop: meta/gui/avalonia-xaml-playground.desktop
    plugs:
      - desktop
      - desktop-legacy
      - dotnet-runtime
      - home
      - opengl
      - unity7
      - wayland

lint:
  ignore:
    - library:
      - usr/lib/**/libICE*
      - usr/lib/**/libicu*
      - usr/lib/**/liblttng-ust-*
      - usr/lib/**/libSM*
      - usr/lib/**/libX11*
      - usr/lib/**/libXau*
      - usr/lib/**/libxcb*
      - usr/lib/**/libXdmcp*
