name: build-and-publish-main

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

env:
  SNAP_NAME: avalonia-xaml-playground

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      id: checkout
    - id: prepare-sha
      run: echo "GIT_SHA=$(git show -s --format=%h)" > "$GITHUB_OUTPUT"
    - uses: snapcore/action-build@v1
      id: build
    - uses: actions/upload-artifact@v4
      id: upload-artifact
      with:
        name: ${{ env.SNAP_NAME }}-${{ steps.prepare-sha.outputs.GIT_SHA }}
        path: ${{ steps.build.outputs.snap }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/download-artifact@v4
        id: download-artifact
      - name: Gather filename
        id: gather-filename
        env:
          ARTIFACT_PATH: ${{ steps.download-artifact.outputs.download-path }}
          SNAP_NAME: ${{ env.SNAP_NAME }}
        run: |
          tree $ARTIFACT_PATH
          SNAP_FILE_NAME=$(ls ${ARTIFACT_PATH}/${SNAP_NAME}*/${SNAP_NAME}*.snap)
          echo "SNAP_PATH=${SNAP_FILE_NAME}" >> "$GITHUB_OUTPUT"
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.gather-filename.outputs.SNAP_PATH }}
          release: edge
