name: build-and-publish-main

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

env:
  SNAP_NAME: avalonia-xaml-playground

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
    - uses: actions/checkout@v4
      id: checkout
    - uses: snapcore/action-build@v1
      id: build
      env:
        SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: "1"
      with:
        snapcraft-channel: latest/edge
        snapcraft-args: --verbose
    - uses: actions/upload-artifact@v4
      id: upload-artifact
      with:
        name: ${{ steps.build.outputs.snap }}
        path: ${{ steps.build.outputs.snap }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/download-artifact@v4
        id: download-artifact
        with:
          pattern: ${{ env.SNAP_NAME }}_*_${{ matrix.arch }}.snap
      - name: Gather filename
        id: gather-filename
        env:
          ARTIFACT_PATH: ${{ steps.download-artifact.outputs.download-path }}
          SNAP_NAME: ${{ env.SNAP_NAME }}
        run: |
          tree $ARTIFACT_PATH
          SNAP_FILE_NAME=$(ls ${ARTIFACT_PATH}/${SNAP_NAME}*/${SNAP_NAME}*.snap)
          echo "SNAP_PATH=${SNAP_FILE_NAME}" >> "$GITHUB_OUTPUT"
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.gather-filename.outputs.SNAP_PATH }}
          release: edge
